language: generic
sudo: required
services:
  - docker
  
before-install:
  - docker build -t kanchancse/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kanchancse/docker-react npm run test -- --coverage